name: deploy to aliyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # npm install
      - name: npm install and build
        run: |
          npm install
        env:
          CI: true
      
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./"
          REMOTE_HOST: "118.190.209.112"
          REMOTE_USER: "root"
          TARGET: "/home/wwwroot/blog.alizeegod.com"
      # Deploy
      #- name: deploy to server
      #  uses: AEnterprise/rsync-deploy@v1.0
      #  env:
       #   DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #  ARGS: "-e -c -r --delete"
        #  SERVER_PORT: '22'
         # FOLDER: "./"
         # SERVER_IP: '118.190.209.112'
         # USERNAME: 'root'
          #SERVER_DESTINATION: "/home/wwwroot/blog.alizeegod.com"
